export const chatData = [
    {
        id: 1,
        senderId: 1,
        receiverId: 2,
        sender: "John",
        receiver: "Jane",
        message: "Hello!",
        timestamp: "2023-10-01T10:00:00Z",
    },
    {
        id: 2,
        senderId: 2,
        receiverId: 1,
        sender: "Jane",
        receiver: "John",
        message: "Hi there!",
        timestamp: "2023-10-01T10:01:00Z",
    },
    {
        id: 3,
        senderId: 1,
        receiverId: 2,
        sender: "John",
        receiver: "Jane",
        message: "How are you?",
        timestamp: "2023-10-01T10:02:00Z",
    },
    {
        id: 4,
        senderId: 2,
        receiverId: 1,
        sender: "Jane",
        receiver: "John",
        message: "I'm good, thanks! How about you?",
        timestamp: "2023-10-01T10:03:00Z",
    },
    {
        id: 5,
        senderId: 1,
        receiverId: 2,
        sender: "John",
        receiver: "Jane",
        message: "Doing well! Just working on some projects.",
        timestamp: "2023-10-01T10:04:00Z",
    },
    {
        id: 6,
        senderId: 2,
        receiverId: 1,
        sender: "Jane",
        receiver: "John",
        message: "That sounds interesting! What kind of projects?",
        timestamp: "2023-10-01T10:05:00Z",
    },
    {
        id: 7,
        senderId: 1,
        receiverId: 2,
        sender: "John",
        receiver: "Jane",
        message: "I'm working on a web app.",
        timestamp: "2023-10-01T10:06:00Z",
    },
    {
        id: 8,
        senderId: 2,
        receiverId: 1,
        sender: "Jane",
        receiver: "John",
        message: "Nice! I love web development.",
        timestamp: "2023-10-01T10:07:00Z",
    },
    {
        id: 9,
        senderId: 1,
        receiverId: 2,
        sender: "John",
        receiver: "Jane",
        message: "Me too! It's so much fun.",
        timestamp: "2023-10-01T10:08:00Z",
    },
    {
        id: 10,
        senderId: 2,
        receiverId: 1,
        sender: "Jane",
        receiver: "John",
        message: "Absolutely! Do you have any favorite frameworks?",
        timestamp: "2023-10-01T10:09:00Z",
    },

    {
        id: 11,
        senderId: 3,
        receiverId: 2,
        sender: "Alice",
        receiver: "Jane",
        message: "I really like React.",
        timestamp: "2023-10-01T10:10:00Z",
    },
    {
        id: 12,
        senderId: 2,
        receiverId: 3,
        sender: "Jane",
        receiver: "Alice",
        message: "React is great! I enjoy using it too.",
        timestamp: "2023-10-01T10:11:00Z",
    },
    {
        id: 13,
        senderId: 3,
        receiverId: 2,
        sender: "Alice",
        receiver: "Jane",
        message: "Have you tried Next.js?",
        timestamp: "2023-10-01T10:12:00Z",
    },
    {
        id: 14,
        senderId: 2,
        receiverId: 3,
        sender: "Jane",
        receiver: "Alice",
        message: "Yes! It's awesome for server-side rendering.",
        timestamp: "2023-10-01T10:13:00Z",
    },
    {
        id: 15,
        senderId: 3,
        receiverId: 2,
        sender: "Alice",
        receiver: "Jane",
        message: "I love the performance improvements.",
        timestamp: "2023-10-01T10:14:00Z",
    },

    {
        id: 16,
        senderId: 4,
        receiverId: 2,
        sender: "Bob",
        receiver: "Jane",
        message: "Hey Jane! What are you up to?",
        timestamp: "2023-10-01T10:15:00Z",
    },
    {
        id: 17,
        senderId: 2,
        receiverId: 4,
        sender: "Jane",
        receiver: "Bob",
        message: "Not much, just chatting with friends. How about you?",
        timestamp: "2023-10-01T10:16:00Z",
    },
    {
        id: 18,
        senderId: 4,
        receiverId: 2,
        sender: "Bob",
        receiver: "Jane",
        message: "Just finished a project. Feeling accomplished!",
        timestamp: "2023-10-01T10:17:00Z",
    },
    {
        id: 19,
        senderId: 2,
        receiverId: 4,
        sender: "Jane",
        receiver: "Bob",
        message: "That's awesome! What was the project about?",
        timestamp: "2023-10-01T10:18:00Z",
    },
    {
        id: 20,
        senderId: 4,
        receiverId: 2,
        sender: "Bob",
        receiver: "Jane",
        message: "It was a web app for tracking tasks.",
        timestamp: "2023-10-01T10:19:00Z",
    },

    {
        id: 21,
        senderId: 5,
        receiverId: 2,
        sender: "Charlie",
        receiver: "Jane",
        message: "Hi Jane! How's it going?",
        timestamp: "2023-10-01T10:20:00Z",
    },
    {
        id: 22,
        senderId: 2,
        receiverId: 5,
        sender: "Jane",
        receiver: "Charlie",
        message: "Hey Charlie! I'm doing well. What about you?",
        timestamp: "2023-10-01T10:21:00Z",
    },
    {
        id: 23,
        senderId: 5,
        receiverId: 2,
        sender: "Charlie",
        receiver: "Jane",
        message: "Just working on some coding challenges.",
        timestamp: "2023-10-01T10:22:00Z",
    },
    {
        id: 24,
        senderId: 2,
        receiverId: 5,
        sender: "Jane",
        receiver: "Charlie",
        message: "That sounds fun! Which platform are you using?",
        timestamp: "2023-10-01T10:23:00Z",
    },
    {
        id: 25,
        senderId: 5,
        receiverId: 2,
        sender: "Charlie",
        receiver: "Jane",
        message: "I'm using LeetCode. It's great for practice.",
        timestamp: "2023-10-01T10:24:00Z",
    },
];
